config/routes.rb
Rails.application.routes.draw do
  resources :bebida_nao_alcoolicas
  resources :bebida_alcoolicas
  resources :pedido_clientes
  resources :pedido_fornecedors
  resources :funcionarios
  resources :fornecedors
  root "funcionarios#index"

  get "/funcionarios", to: "funcionarios#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/fornecedor.rb
class Fornecedor < ApplicationRecord
end

app/controllers/fornecedors_controller.rb
class FornecedorsController < ApplicationController
  before_action :set_fornecedor, only: %i[ show edit update destroy ]

  # GET /fornecedors or /fornecedors.json
  def index
    @fornecedors = Fornecedor.all
  end

  # GET /fornecedors/1 or /fornecedors/1.json
  def show
  end

  # GET /fornecedors/new
  def new
    @fornecedor = Fornecedor.new
  end

  # GET /fornecedors/1/edit
  def edit
  end

  # POST /fornecedors or /fornecedors.json
  def create
    @fornecedor = Fornecedor.new(fornecedor_params)

    respond_to do |format|
      if @fornecedor.save
        format.html { redirect_to @fornecedor, notice: "Fornecedor was successfully created." }
        format.json { render :show, status: :created, location: @fornecedor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fornecedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fornecedors/1 or /fornecedors/1.json
  def update
    respond_to do |format|
      if @fornecedor.update(fornecedor_params)
        format.html { redirect_to @fornecedor, notice: "Fornecedor was successfully updated." }
        format.json { render :show, status: :ok, location: @fornecedor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fornecedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fornecedors/1 or /fornecedors/1.json
  def destroy
    @fornecedor.destroy
    respond_to do |format|
      format.html { redirect_to fornecedors_url, notice: "Fornecedor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fornecedor
      @fornecedor = Fornecedor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fornecedor_params
      params.require(:fornecedor).permit(:cnpj, :nome)
    end
end

app/helpers/fornecedors_helper.rb
module FornecedorsHelper
end

app/views/fornecedors/_form.html.erb
<%= form_with(model: fornecedor) do |form| %>
  <% if fornecedor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fornecedor.errors.count, "error") %> prohibited this fornecedor from being saved:</h2>

      <ul>
        <% fornecedor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cnpj %>
    <%= form.number_field :cnpj %>
  </div>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fornecedors/edit.html.erb
<h1>Editing Fornecedor</h1>

<%= render 'form', fornecedor: @fornecedor %>

<%= link_to 'Show', @fornecedor %> |
<%= link_to 'Back', fornecedors_path %>

app/views/fornecedors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fornecedors</h1>

<table>
  <thead>
    <tr>
      <th>Cnpj</th>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fornecedors.each do |fornecedor| %>
      <tr>
        <td><%= fornecedor.cnpj %></td>
        <td><%= fornecedor.nome %></td>
        <td><%= link_to 'Show', fornecedor %></td>
        <td><%= link_to 'Edit', edit_fornecedor_path(fornecedor) %></td>
        <td><%= link_to 'Destroy', fornecedor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fornecedor', new_fornecedor_path %>

app/views/fornecedors/new.html.erb
<h1>New Fornecedor</h1>

<%= render 'form', fornecedor: @fornecedor %>

<%= link_to 'Back', fornecedors_path %>

app/views/fornecedors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cnpj:</strong>
  <%= @fornecedor.cnpj %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @fornecedor.nome %>
</p>

<%= link_to 'Edit', edit_fornecedor_path(@fornecedor) %> |
<%= link_to 'Back', fornecedors_path %>