config/routes.rb
Rails.application.routes.draw do
  resources :bebida_nao_alcoolicas
  resources :bebida_alcoolicas
  resources :pedido_clientes
  resources :pedido_fornecedors
  resources :funcionarios
  resources :fornecedors
  root "funcionarios#index"

  get "/funcionarios", to: "funcionarios#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/bebida_alcoolica.rb
class BebidaAlcoolica < ApplicationRecord
end

app/controllers/bebida_alcoolicas_controller.rb
class BebidaAlcoolicasController < ApplicationController
  before_action :set_bebida_alcoolica, only: %i[ show edit update destroy ]

  # GET /bebida_alcoolicas or /bebida_alcoolicas.json
  def index
    @bebida_alcoolicas = BebidaAlcoolica.all
  end

  # GET /bebida_alcoolicas/1 or /bebida_alcoolicas/1.json
  def show
  end

  # GET /bebida_alcoolicas/new
  def new
    @bebida_alcoolica = BebidaAlcoolica.new
  end

  # GET /bebida_alcoolicas/1/edit
  def edit
  end

  # POST /bebida_alcoolicas or /bebida_alcoolicas.json
  def create
    @bebida_alcoolica = BebidaAlcoolica.new(bebida_alcoolica_params)

    respond_to do |format|
      if @bebida_alcoolica.save
        format.html { redirect_to @bebida_alcoolica, notice: "Bebida alcoolica was successfully created." }
        format.json { render :show, status: :created, location: @bebida_alcoolica }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bebida_alcoolica.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bebida_alcoolicas/1 or /bebida_alcoolicas/1.json
  def update
    respond_to do |format|
      if @bebida_alcoolica.update(bebida_alcoolica_params)
        format.html { redirect_to @bebida_alcoolica, notice: "Bebida alcoolica was successfully updated." }
        format.json { render :show, status: :ok, location: @bebida_alcoolica }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bebida_alcoolica.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bebida_alcoolicas/1 or /bebida_alcoolicas/1.json
  def destroy
    @bebida_alcoolica.destroy
    respond_to do |format|
      format.html { redirect_to bebida_alcoolicas_url, notice: "Bebida alcoolica was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bebida_alcoolica
      @bebida_alcoolica = BebidaAlcoolica.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bebida_alcoolica_params
      params.require(:bebida_alcoolica).permit(:codigo_de_barras, :nome, :valor, :quantidade_estoque, :identidade_cliente)
    end
end

app/helpers/bebida_alcoolicas_helper.rb
module BebidaAlcoolicasHelper
end

app/views/bebida_alcoolicas/_form.html.erb
<%= form_with(model: bebida_alcoolica) do |form| %>
  <% if bebida_alcoolica.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bebida_alcoolica.errors.count, "error") %> prohibited this bebida_alcoolica from being saved:</h2>

      <ul>
        <% bebida_alcoolica.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :codigo_de_barras %>
    <%= form.text_field :codigo_de_barras %>
  </div>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :valor %>
    <%= form.text_field :valor %>
  </div>

  <div class="field">
    <%= form.label :quantidade_estoque %>
    <%= form.number_field :quantidade_estoque %>
  </div>

  <div class="field">
    <%= form.label :identidade_cliente %>
    <%= form.text_field :identidade_cliente %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bebida_alcoolicas/edit.html.erb
<h1>Editing Bebida Alcoolica</h1>

<%= render 'form', bebida_alcoolica: @bebida_alcoolica %>

<%= link_to 'Show', @bebida_alcoolica %> |
<%= link_to 'Back', bebida_alcoolicas_path %>

app/views/bebida_alcoolicas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bebida Alcoolicas</h1>

<table>
  <thead>
    <tr>
      <th>Codigo de barras</th>
      <th>Nome</th>
      <th>Valor</th>
      <th>Quantidade estoque</th>
      <th>Identidade cliente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bebida_alcoolicas.each do |bebida_alcoolica| %>
      <tr>
        <td><%= bebida_alcoolica.codigo_de_barras %></td>
        <td><%= bebida_alcoolica.nome %></td>
        <td><%= bebida_alcoolica.valor %></td>
        <td><%= bebida_alcoolica.quantidade_estoque %></td>
        <td><%= bebida_alcoolica.identidade_cliente %></td>
        <td><%= link_to 'Show', bebida_alcoolica %></td>
        <td><%= link_to 'Edit', edit_bebida_alcoolica_path(bebida_alcoolica) %></td>
        <td><%= link_to 'Destroy', bebida_alcoolica, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bebida Alcoolica', new_bebida_alcoolica_path %>

app/views/bebida_alcoolicas/new.html.erb
<h1>New Bebida Alcoolica</h1>

<%= render 'form', bebida_alcoolica: @bebida_alcoolica %>

<%= link_to 'Back', bebida_alcoolicas_path %>

app/views/bebida_alcoolicas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo de barras:</strong>
  <%= @bebida_alcoolica.codigo_de_barras %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @bebida_alcoolica.nome %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @bebida_alcoolica.valor %>
</p>

<p>
  <strong>Quantidade estoque:</strong>
  <%= @bebida_alcoolica.quantidade_estoque %>
</p>

<p>
  <strong>Identidade cliente:</strong>
  <%= @bebida_alcoolica.identidade_cliente %>
</p>

<%= link_to 'Edit', edit_bebida_alcoolica_path(@bebida_alcoolica) %> |
<%= link_to 'Back', bebida_alcoolicas_path %>