config/routes.rb
Rails.application.routes.draw do
  resources :bebida_nao_alcoolicas
  resources :bebida_alcoolicas
  resources :pedido_clientes
  resources :pedido_fornecedors
  resources :funcionarios
  resources :fornecedors
  root "funcionarios#index"

  get "/funcionarios", to: "funcionarios#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/pedido_fornecedor.rb
class PedidoFornecedor < ApplicationRecord
    has_many :pedido_produtos
end

app/controllers/pedido_fornecedors_controller.rb
class PedidoFornecedorsController < ApplicationController
  before_action :set_pedido_fornecedor, only: %i[ show edit update destroy ]

  # GET /pedido_fornecedors or /pedido_fornecedors.json
  def index
    @pedido_fornecedors = PedidoFornecedor.all
  end

  # GET /pedido_fornecedors/1 or /pedido_fornecedors/1.json
  def show
  end

  # GET /pedido_fornecedors/new
  def new
    @pedido_fornecedor = PedidoFornecedor.new
  end

  # GET /pedido_fornecedors/1/edit
  def edit
  end

  # POST /pedido_fornecedors or /pedido_fornecedors.json
  def create
    @pedido_fornecedor = PedidoFornecedor.new(pedido_fornecedor_params)

    respond_to do |format|
      if @pedido_fornecedor.save
        format.html { redirect_to @pedido_fornecedor, notice: "Pedido fornecedor was successfully created." }
        format.json { render :show, status: :created, location: @pedido_fornecedor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pedido_fornecedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pedido_fornecedors/1 or /pedido_fornecedors/1.json
  def update
    respond_to do |format|
      if @pedido_fornecedor.update(pedido_fornecedor_params)
        format.html { redirect_to @pedido_fornecedor, notice: "Pedido fornecedor was successfully updated." }
        format.json { render :show, status: :ok, location: @pedido_fornecedor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pedido_fornecedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedido_fornecedors/1 or /pedido_fornecedors/1.json
  def destroy
    @pedido_fornecedor.destroy
    respond_to do |format|
      format.html { redirect_to pedido_fornecedors_url, notice: "Pedido fornecedor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido_fornecedor
      @pedido_fornecedor = PedidoFornecedor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pedido_fornecedor_params
      params.require(:pedido_fornecedor).permit(:quantidade, :valor)
    end
end

app/helpers/pedido_fornecedors_helper.rb
module PedidoFornecedorsHelper
end

app/views/pedido_fornecedors/_form.html.erb
<%= form_with(model: pedido_fornecedor) do |form| %>
  <% if pedido_fornecedor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pedido_fornecedor.errors.count, "error") %> prohibited this pedido_fornecedor from being saved:</h2>

      <ul>
        <% pedido_fornecedor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :quantidade %>
    <%= form.number_field :quantidade %>
  </div>

  <div class="field">
    <%= form.label :valor %>
    <%= form.text_field :valor %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pedido_fornecedors/edit.html.erb
<h1>Editing Pedido Fornecedor</h1>

<%= render 'form', pedido_fornecedor: @pedido_fornecedor %>

<%= link_to 'Show', @pedido_fornecedor %> |
<%= link_to 'Back', pedido_fornecedors_path %>

app/views/pedido_fornecedors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pedido Fornecedors</h1>

<table>
  <thead>
    <tr>
      <th>Quantidade</th>
      <th>Valor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pedido_fornecedors.each do |pedido_fornecedor| %>
      <tr>
        <td><%= pedido_fornecedor.quantidade %></td>
        <td><%= pedido_fornecedor.valor %></td>
        <td><%= link_to 'Show', pedido_fornecedor %></td>
        <td><%= link_to 'Edit', edit_pedido_fornecedor_path(pedido_fornecedor) %></td>
        <td><%= link_to 'Destroy', pedido_fornecedor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pedido Fornecedor', new_pedido_fornecedor_path %>

app/views/pedido_fornecedors/new.html.erb
<h1>New Pedido Fornecedor</h1>

<%= render 'form', pedido_fornecedor: @pedido_fornecedor %>

<%= link_to 'Back', pedido_fornecedors_path %>

app/views/pedido_fornecedors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quantidade:</strong>
  <%= @pedido_fornecedor.quantidade %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @pedido_fornecedor.valor %>
</p>

<%= link_to 'Edit', edit_pedido_fornecedor_path(@pedido_fornecedor) %> |
<%= link_to 'Back', pedido_fornecedors_path %>